#!/bin/bash

# Generate Random Files
# generate file of various sizes with random contents for test copy offloading
# Test based on (https://lwn.net/Articles/658718/)
# How to?: by util 'dd'(http://superuser.com/questions/470949/how-do-i-create-a-1gb-random-file-in-linux)

RND=/dev/urandom
DIR=`git rev-parse --show-toplevel`/test/copy_file_range/

for ((i=1;i<11;i++)); do
    if [ $i -eq 7 ]; then
        i=10
    fi
    size=`expr "$i" "*" "512"`
    output=origin_$size.txt
    dd if=$RND of=$DIR$output count=$i 2>/dev/null
done

echo "Generated origin files for test,'copy_file_range()'"
