#!/usr/bin/env python3
#-*-coding:utf-8-*-

import sys
import os
import json
import argparse

def script_dir():
    return sys.path[0]

BASE_EVAL_PATH = '/'.join(script_dir().split('/')[:-2])+"/feature-evals"

def print_help():
    print("print_help")

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

def shell_command(command, error_str='', print_on_error=True, exit_on_error=True) :
    ret = os.system(command)
    if ret :  
        if print_on_error :
            if error_str :
                eprint(error_str)
            else :  
                eprint("failed : "+command)
        if exit_on_error :
            exit(1)
    return ret  

def add_feature(features, fname):
	eval_dir = input('feature evauation dir : ') #상대경로일 경우 feature_eval에서
	if not eval_dir.startswith('/'):
		eval_dir = BASE_EVAL_PATH+'/'+eval_dir
	print('----before----')
	before = dict()
	before['eval_script_name'] = input('before - feature evaluation script name : ') #TODO check if it exists
	before['version'] = input('before - kerenl version : ')
	before['config'] = dict()
	j=0
	print('before - kernel configs(Crtl+D to stop) : ')
	while True :
		try:
			config_name = input('before - kernel config[%d] name : ' % j)
			config_value = input('before - kernel config[%d] value : ' % j)
			before['config'][config_name] = config_value
			j += 1
		except EOFError:
			print()
			break

	after = dict()
	if input('same kerenl as before?(y/N) : ').lower() != 'y':
		print('----after----')
		after['eval_script_name'] = input('after - feature evaluation script name : ') #TODO check if it exists
		after['version'] = input('after - kerenl version : ')
		after['config'] = dict()
		j=0
		print('after - kernel configs(Crtl+D to stop) : ')
		while True:
			try:
				config_name = input('after - kernel config[%d] name : ' % j)
				config_value = input('after - kernel config[%d] value : ' % j)
				after['config'][config_name] = config_value
				j += 1
			except EOFError:
				break
	else:
		after = before.copy()
		after['eval_script_name'] = input('after - feature evaluation script name : ') #TODO check if it exists

	feature = dict()
	feature['evaluation_dir'] = eval_dir
	feature['before'] = before
	feature['after'] = after
	features[fname] = feature
				

def del_feature(features, fname):
	del features[fname]

def show_feature(features, fname):
	try:
		feature = features[fname]
	except KeyError:
		eprint('feature not found.')
		exit(1)
	print('\tfeature evaluation script dir : '+feature['evaluation_dir'])

	before = feature['before']
	after = feature['after']
	print('\tbefore : ')
	print('\t\tfeature evaluation script name : '+before['eval_script_name'])
	print('\t\tkernel versoin : %s' % before['version'])
	print('\t\tkernel configs : ')
	f_configs = before['config']
	for k,v in f_configs.items():
		print('\t\t '+k+'='+str(v))
	print('\tafter : ')
	print('\t\tfeature evaluation script name : '+after['eval_script_name'])
	print('\t\tkernel versoin : %s' % after['version'])
	print('\t\tkernel configs : ')
	f_configs = after['config']
	for k, v in f_configs.items():
		print('\t\t ' + k + '=' + str(v))

def list_feature(features, opt = '--default'):
	opts = ['--details', '--default']
	if opt not in opts:
		raise Exception('invalid option')
	if opt == '--default':
		for fname in features.keys():
			print(fname)
	elif opt == '--details':
		for fname in features.keys():
			show_feature(features, fname)


parser = argparse.ArgumentParser(description='feature evaluation control : edit feature_eval.conf for lkfes')

parsers = parser.add_subparsers(help='actions')
parser_add = parsers.add_parser('add', help='add new evaluating feature')
parser_add.set_defaults(action='add')
parser_add.add_argument('feature', help='adding feature name')
parser_del = parsers.add_parser('del', help='delete evaluating feature')
parser_del.set_defaults(action='del')
parser_del.add_argument('feature', help='deleting feature name')
parser_list = parsers.add_parser('list', help='list evaluating features')
parser_list.set_defaults(action='list')
parser_list.add_argument('--details', action='store_true', help='list with detail infos')
parser_show = parsers.add_parser('show', help='show evaluating feature')
parser_show.set_defaults(action='show')
parser_show.add_argument('feature', help='adding feature name')

args = parser.parse_args()

if len(sys.argv) == 1:
	print(parser.print_help())
	exit(1)

feconf_file_name = script_dir()+'/feature_eval.conf'
feconf_file = ''
features = ''
if os.path.exists(feconf_file_name) :
	feconf_file = open(feconf_file_name, 'r')
	features = json.load(feconf_file)
	feconf_file.close()
else:
	features = json.loads('{}')

current_module = sys.modules[__name__]
command_handler = getattr(current_module, args.action+'_feature')
if len(sys.argv) > 2:
	command_handler(features, sys.argv[2])
else:
	command_handler(features)

feconf_file = open(feconf_file_name, 'w+')
json.dump(features, feconf_file)
feconf_file.close()

print('done')
